// src/utils/types.ts
export const TYPES = {
    PrismaClient: Symbol.for('PrismaClient'),
    Routes: Symbol.for('Routes'),
    HealthController: Symbol.for('HealthController'),
    ClassifierController: Symbol.for('ClassifierController'),
    UserRepository: Symbol.for('UserRepository'),
    UserService: Symbol.for('UserService'),
    UserController: Symbol.for('UserController'),
    UserRoutes: Symbol.for('UserRoutes'),
    TransactionRepository: Symbol.for('TransactionRepository'),
    TransactionService: Symbol.for('TransactionService'),
    TransactionController: Symbol.for('TransactionController'),
    TransactionRoutes: Symbol.for('TransactionRoutes'),
    TransactionBudgetingRepository: Symbol.for('TransactionBudgetingRepository'),
    TransactionBudgetingService: Symbol.for('TransactionBudgetingService'),
    TransactionBudgetingController: Symbol.for('TransactionBudgetingController'),
    TransactionBudgetingRoutes: Symbol.for('TransactionBudgetingRoutes'),
    TransactionEvaluationRepository: Symbol.for('TransactionEvaluationRepository'),
    TransactionEvaluationService: Symbol.for('TransactionEvaluationService'),
    TransactionEvaluationController: Symbol.for('TransactionEvaluationController'),
    TransactionEvaluationRoutes: Symbol.for('TransactionEvaluationRoutes'),
    OtpVerificationRepository: Symbol.for('OtpVerificationRepository'),
    OtpVerificationService: Symbol.for('OtpVerificationService'),
    OtpVerificationController: Symbol.for('OtpVerificationController'),
    OtpVerificationRoutes: Symbol.for('OtpVerificationRoutes'),
};
